-- Autogenerated by sqlweld
SELECT
  items.id,
  items.app_id,
  items.data AS "data: AppItemData",
  items.updated_at,
  items.created_at,
  items.state_key,
  items.persistent,
  items.dismissed,
  array_agg(jsonb_build_object('id', noti.id, 'data', noti.data, 'dismissed',
    noti.dismissed)) FILTER (WHERE noti.id IS NOT NULL) AS "notify: Vec<Notification>"
FROM
  items
  LEFT JOIN item_notifications noti ON items.id = noti.item_id
    AND items.app_id = noti.app_id
    AND NOT noti.dismissed
WHERE
  items.app_id = $1
GROUP BY
  items.id,
  items.app_id
