description = "Summarize Comments"

system_prompt = '''
You summarize the Hacker News comments section.
Note any interesting concepts or anecdotes, and the sentiment in the comments.
Focus on comments related to the title.
Do not include how many comments there are or when they were made.
'''

template = '''
Below are comments on a web page titled {{title}}.

{{extra}}


The comments' summary is:
'''

model.context.trim_args = ["extra"]

[options]
title = { type = "string" }

