[package]
name = "glance-core"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
effectum = "0.3.0"
error-stack = { version = "0.4.1", features = ["eyre"] }
flume = { version = "0.11.0", default-features = false }
glance-app = { path = "../app-rust", features = ["sqlx"] }
itertools = "0.11.0"
notify-debouncer-mini = { version = "0.4.1", optional = true }
serde = { version = "1.0.189", features = ["derive"] }
serde_json = "1.0.107"
sqlx = { version = "0.7.2", features = ["postgres", "runtime-tokio", "tls-rustls"] }
thiserror = "1.0.50"
tokio = { version = "1.34.0", features = ["full", "tracing"] }

[features]
default = ["fs-source"]
fs-source = ["notify-debouncer-mini"]
