/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppData {
  items?: AppDataItem[];
  /**
   * The name of the app
   */
  name: string;
  /**
   * The path at which this app is installed
   */
  path: string;
  /**
   * Request that the platform run the app at the specified schedule, if it does not have its own methods of scheduling updates
   */
  schedule?: AppDataSchedule[];
  /**
   * If false, the app does not keep its own state, so the platform should do a closer diff to see if an item has changed since the last write If true, the app can just check the updated timestamp to see if an item has changed
   */
  stateful?: boolean;
}
export interface AppDataItem {
  /**
   * Extra structured data for use by chart or other formatters
   */
  data?: {
    [k: string]: unknown;
  };
  /**
   * Whether the item can be dismissed by the viewer
   */
  dismissible?: boolean;
  /**
   * HTML to display for the item's label
   */
  html: string;
  id: string;
  /**
   * Notifications for this item
   */
  notify?: Notification[];
  /**
   * Date the item was last updated
   */
  updated: string;
}
export interface Notification {
  html: string;
  icon?: string | null;
  id: string;
}
export interface AppDataSchedule {
  /**
   * Arguments to pass to the app
   */
  arguments?: string[];
  /**
   * The cron schedule for the app
   */
  cron: string;
}
