/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppData {
  app: {
    name: string;
    /**
     * If true, the app does not keep its own state, so the platform should do a closer diff to see if an item has changed since the last write
     */
    stateless?: boolean;
    [k: string]: unknown;
  };
  items: {
    id: string;
    /**
     * HTML to display for the item's label
     */
    html: string;
    /**
     * Extra structured data for use by chart or other formatters
     */
    data?: {
      [k: string]: unknown;
    };
    /**
     * Date the item was last updated
     */
    updated: string;
    /**
     * Charts to display for this item
     */
    charts?: Chart[];
    notify?: Notification[];
    [k: string]: unknown;
  }[];
  [k: string]: unknown;
}
export interface Chart {
  [k: string]: unknown;
}
export interface Notification {
  id: string;
  icon?: string;
  html: string;
  [k: string]: unknown;
}
